### ISSUE TITLE
Support for Python 3.8.10?

### ISSUE THREAD

**Issue by marklit** [Apakottur/shpyx#20]
The package installs via ``python -m pip install shpyx`` without issue but I'm greeting with the following when I try to import it.

```python
>>> import shpyx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mark/.airflow/lib/python3.8/site-packages/shpyx/__init__.py", line 12, in <module>
    from .cmd_runner import ShellCmdRunner, run
  File "/home/mark/.airflow/lib/python3.8/site-packages/shpyx/cmd_runner.py", line 57, in <module>
    class ShellCmdRunner:
  File "/home/mark/.airflow/lib/python3.8/site-packages/shpyx/cmd_runner.py", line 69, in ShellCmdRunner
    def _log(msg: bytes | str) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

Are you able to add support for Python 3.8 as well?

**Comment by Apakottur** [comment]
Hey, glad that you're still using the library :)

Thanks for pointing this out, I was making some changes and did not think about backwards compatibility with older Python versions.

I removed the problematic code in https://github.com/Apakottur/shpyx/pull/21 and updated the package on pypi.

Can you please check if `shpyx==0.0.14` works fine again with your Python version?

**Comment by marklit** [comment]
Spot on, works perfectly now. Thanks for the quick turnaround!
